# -*- coding: utf-8 -*-
"""Day 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152auZ77yEBAFbZbJY5u8wrWGfnxNtIUr
"""

# Today, I explored **variables, data types, and user input/output** in Python.

# ## Goals of this Notebook
# - Understand what variables are and why they are useful
# - Explore different data types in Python
# - Learn how to take input from users
# - Print clear output messages

# 📌 Variables in Python
# Variables are like containers that hold values.
# Here we define some variables of different types.

name = "Rithwik"       # String (text)
age = 18               # Integer (whole number)
height = 5.8          # Float (decimal number)
is_student = True      # Boolean (True/False)

print("Name:", name)
print("Age:", age)
print("Height:", height)
print("Student:", is_student)

## 🔢 Python Data Types

# In Python, common data types include:
# - **String** → text like `"Hello"`
# - **Integer** → whole numbers like `10`
# - **Float** → decimal numbers like `3.14`
# - **Boolean** → values `True` or `False`

# 📌 Taking input from the user
# The input() function lets users type something.

user_name = input("Enter your name: ")
print("Hello", user_name, "! Welcome to colab")

# ## 🏋️ Practice Program

# This small program asks for the user's name and age,
# then prints a personalized message

# 🏋️ Practice Program
name = input("Enter your name: ")
age = input("Enter your age: ")

print("=================================")
print("Hello", name + " 👋")
print("You are", age, "years old.")
print("Glad to see you coding in Python 🚀")
print("=================================")

# In this notebook, I learned:
# - How to declare and use variables
# - Different data types in Python
# - How to use input() and print() effectively

# This is my **Day 6 progress** in the #100DaysOfCode challenge.
# Uploaded to GitHub as part of my learning portfolio.