# -*- coding: utf-8 -*-
"""Day 8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wrxBPXPzJWQt0qlty4AMBbHJV1PcL9rk

# Day 8 - Loops, Functions, and String Operations

👋 Today I practiced three important concepts in Python:
1. Loops (`for`, `while`) - repeating tasks
2. Functions - reusable code blocks
3. String operations - working with text effectively

At the end, I built **2 small projects** using these concepts.
"""

# 📌 For Loop Example: Print numbers 1 to 5
for i in range(1, 6):
    print(i)

# 📌 While Loop Example: Countdown
count = 5
while count > 0:
    print("Countdown:", count)
    count -= 1
print("Boom! 🚀")

# 📌 Function Example
def greet(name):
    return f"Hello, {name}! Welcome to Day 8 🚀"

print(greet("Rithwik"))
print(greet("Python Learner"))

# 📌 String Operations
text = "Python is Awesome"

print("Uppercase:", text.upper())
print("Lowercase:", text.lower())
print("Length:", len(text))
print("First 6 chars:", text[:6])
print("Replaced:", text.replace("Awesome", "Powerful"))

"""## 🏋️ Mini Project 1 - Multiplication Table Generator

"""

# 🏋️ Mini Project 1 - Multiplication Table Generator

number = int(input("Enter a number: "))

print(f"Multiplication Table of {number}")
for i in range(1, 11):
    print(f"{number} x {i} = {number*i}")

"""## 🏋️ Mini Project 2 - Word Counter
This program takes a sentence and counts how many words it has.

"""

# 🏋️ Mini Project 2 - Word Counter

sentence = input("Enter a sentence: ")

# Split sentence into words
words = sentence.split()

print("Your sentence has", len(words), "words.")

"""## ✅ Summary

In this notebook, I learned:
- How to use loops (for, while)
- How to create and use functions
- String operations like slicing, replacing, and length checking
- Built 2 small projects: **Multiplication Table Generator** and **Word Counter**

This is my **Day 8 progress** in the #100DaysOfCode challenge.  
Uploaded to GitHub as part of my learning portfolio.

"""