# -*- coding: utf-8 -*-
"""Day 9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xf-zTo4StHICO_fd50y9Y__XDk286QRI

# Day 9 - Lists, Dictionaries, and File Handling

👋 Today I explored three very important parts of Python:
1. **Lists** → storing multiple values in a single variable  
2. **Dictionaries** → storing data in key-value pairs  
3. **File Handling** → reading from and writing to files  

At the end, I built a **mini project: Student Report Card System**.
"""

# 📌 Lists in Python
fruits = ["apple", "banana", "cherry"]

print("All fruits:", fruits)
print("First fruit:", fruits[0])
print("Last fruit:", fruits[-1])

# Adding a new fruit
fruits.append("mango")
print("Updated fruits:", fruits)

# 📌 Dictionaries in Python
student = {
    "name": "Rithwik",
    "age": 18,
    "course": "CSE AI & ML"
}

print("Student Name:", student["name"])
print("Student Age:", student["age"])

# Adding a new key-value
student["grade"] = "A"
print("Updated student dictionary:", student)

# 📌 File Handling - Writing to a file

with open("notes.txt", "w") as file:
    file.write("This is Day 9 of my 100 Days of Code.\n")
    file.write("I am learning lists, dictionaries, and file handling.\n")

print("Data written to notes.txt ✅")

# 📌 File Handling - Reading from a file

with open("notes.txt", "r") as file:
    content = file.read()

print("File Content:\n", content)

"""## 🏋️ Mini Project - Student Report Card System

This project stores student data in a dictionary,  
writes it to a file, and then reads it back.

"""

# 🏋️ Mini Project - Student Report Card System

# Step 1: Store student data in a dictionary
student = {
    "name": input("Enter student name: "),
    "maths": int(input("Enter Maths marks: ")),
    "science": int(input("Enter Science marks: ")),
    "english": int(input("Enter English marks: "))
}

# Step 2: Calculate average and grade
average = (student["maths"] + student["science"] + student["english"]) / 3

if average >= 90:
    grade = "A"
elif average >= 75:
    grade = "B"
elif average >= 50:
    grade = "C"
else:
    grade = "F"

student["average"] = average
student["grade"] = grade

# Step 3: Write to file
with open("report_card.txt", "w") as file:
    file.write("Student Report Card\n")
    file.write("====================\n")
    for key, value in student.items():
        file.write(f"{key}: {value}\n")

print("Report card saved to report_card.txt ✅")

# Step 4: Read back the file
with open("report_card.txt", "r") as file:
    report = file.read()

print("\n--- Report Card ---")
print(report)

"""## ✅ Summary

In this notebook, I learned:
- How to store multiple values using **lists**
- How to use **dictionaries** for key-value storage
- How to read/write files using Python's file handling
- Built a **Student Report Card System** mini project

This is my **Day 9 progress** in the #100DaysOfCode challenge.  
Uploaded to GitHub as part of my learning portfolio.

"""