# -*- coding: utf-8 -*-
"""Day-4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o1tHnx0ujhsl6idMOMLoXMdzaS2wTad8
"""

print("This is my Day 4 practice file, uploaded from Colab!")